In [1]:
1+2

3

In [2]:
print(4*5)

20


<h1><font face="Comic Sans MS" size="12" >Numpy</font></h1>


In [3]:
import numpy as np

In [4]:
#creating a one dimensional array
arr1=np.array([1,2,3,4,5])

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


### checkint the size of an array

In [6]:
print(arr1.shape)

(5,)


### reshaping
<p>suppose you want to reshape the array for our instance we have now arr1 and i want to reshape it so i can
call the reshape(number_of_rows,number_of_col) to reshape the array to defined number of rows and col
</p>

In [7]:
arr2=arr1.reshape(1,5)

In [8]:
print(arr2)

[[1 2 3 4 5]]


In [9]:

# Step 1: Create an array
arr1 = np.array([1, 2, 3, 4, 5])

# Step 2: Reshape it into 2D (as given)
arr2 = arr1.reshape(1, 5)

# Step 3: Reshape into 3 dimensions (with dimensions that are compatible)
arr3 = arr1.reshape(1, 5, 1)

# Step 4: Reshape into 4 dimensions
arr4 = arr1.reshape(1, 1, 5, 1)

arr1, arr2, arr3, arr4


(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3, 4, 5]]),
 array([[[1],
         [2],
         [3],
         [4],
         [5]]]),
 array([[[[1],
          [2],
          [3],
          [4],
          [5]]]]))

In [10]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr3=np.ones((3,4,2))

In [12]:
## to print the size of an array
print(arr3.size)
## to print the dimension of an array
print(arr3.ndim)
## to print the size of each item contained in the array
print(arr3.itemsize)
##  to print the data type of the array 
print(arr3.dtype)

24
3
8
float64


In [13]:
# this will give the array of 5 elements
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


## numpy array operations onto it
<p>to perform operations on each element of the array,this will result into a new array</p>

In [14]:
# to find the sqrt of each element in the array
print(np.sqrt(arr1))
# to find the exponent of each element in the array
print(np.exp(arr1))
# to find the sine of each element in the array
print(np.sin(arr1))
# to find the square of each element in the array


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [15]:
print(np.mean(arr1))

3.0


In [16]:
# standard deviation of all element in the array
print(np.std(arr1))

1.4142135623730951


### normalizing the data

In [17]:
data=[2,3.34,.1,2.9]
std_of_data=np.std(data)
mean_of_data=np.mean(data)
print((data-mean_of_data)/std_of_data)


[-0.06834699  1.0091232  -1.59610324  0.65532702]


## finding the median and variance of the data

In [18]:
print(np.median(data))
# finding the variance of the data
print(np.var(data))

2.45
1.5466749999999998


In [19]:
print(data)

[2, 3.34, 0.1, 2.9]


In [20]:
arr1-5

array([-4, -3, -2, -1,  0])

In [21]:
arr1[arr1>2]

array([3, 4, 5])

In [22]:
arr1[(arr1>2) & (arr1<5)]

array([3, 4])

#### this is to show that numpy is not hetereogenous it is rather homogeneous meaning it can store only certain type of data throught out the table

In [23]:
np.array([23,13,12,90,17,'w'])

array(['23', '13', '12', '90', '17', 'w'], dtype='<U21')

## Pandas
### pandas is used for high level requirement,it is heterogenous tabular data storing,it contains series and data frame data structure
### data frame is 2d and series is 1d

In [24]:
import pandas as pd
series=pd.Series([1,9,10,11,23,21])
print(series)

0     1
1     9
2    10
3    11
4    23
5    21
dtype: int64


In [25]:
#creating a dataframe using dictionary of list
dataF1=pd.DataFrame({'name':["john","jack","andrew","elvis"],
                     'age':[12,23,14,15],
                     'weight':[123,321,890,234]})
print(dataF1)

     name  age  weight
0    john   12     123
1    jack   23     321
2  andrew   14     890
3   elvis   15     234


<p>creating data frame using list of dictionary</p>

In [26]:
dataF2=pd.DataFrame([{'name':"mark",'age':23,'occupation':'software engineer'},
                     {'name':"drake",'age':20,'occupation':'tester'},
                     {'name':"mark",'age':24,'occupation':'dev ops'},
                     {'name':"prakhar",'age':23,'occupation':'data science engineer'},
                     {'name':"henry",'age':23,'occupation':'full stack engineer'}
                     ])

In [27]:
print(dataF2)

      name  age             occupation
0     mark   23      software engineer
1    drake   20                 tester
2     mark   24                dev ops
3  prakhar   23  data science engineer
4    henry   23    full stack engineer


#### reading csv file

In [28]:
df=pd.read_csv("./people_info.csv")

In [29]:
df.loc[3]

name                        prakhar
age                              23
occupation    data science engineer
Name: 3, dtype: object

In [30]:
df.iloc[1][1]

C:\Users\Pragya\AppData\Local\Temp\ipykernel_14824\1723490747.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][1]


np.int64(20)

In [31]:
df.loc[0:2]

name  age         occupation
0   mark   23  software engineer
1  drake   20             tester
2   mark   24            dev ops

###  loc and iloc  
<p>loc is labeled base and it can accept boolean value as well ,unlike iloc which cannot accept the boolean values</p>

In [32]:
df.loc[df.age>23]

name  age occupation
2  mark   24    dev ops

In [33]:
df.loc[df.name=="prakhar",['occupation']]="machine learning"

In [34]:
df

name  age           occupation
0     mark   23    software engineer
1    drake   20               tester
2     mark   24              dev ops
3  prakhar   23     machine learning
4    henry   23  full stack engineer

<p>iloc is index based </p>

In [35]:
df.iloc[1:3,1:3]

age occupation
1   20     tester
2   24    dev ops

In [36]:
# when acessing a single whole column then it will result in a series
df['name']

0       mark
1      drake
2       mark
3    prakhar
4      henry
Name: name, dtype: object

In [37]:
df['age']

0    23
1    20
2    24
3    23
4    23
Name: age, dtype: int64

In [38]:
type(df['name'])

pandas.core.series.Series

applying the lmbda function on each element of the row or column 

In [39]:
df['age'].apply(lambda x:x*2)

0    46
1    40
2    48
3    46
4    46
Name: age, dtype: int64

#### i can also write a combination of label and index to acess the value in the data frame

In [40]:
df.loc[df["name"]=="prakhar",'age']
df.loc[2,"age"]

np.int64(24)

In [41]:
df

name  age           occupation
0     mark   23    software engineer
1    drake   20               tester
2     mark   24              dev ops
3  prakhar   23     machine learning
4    henry   23  full stack engineer

In [43]:
df["salary"]=[20000,30000,12300,120000,100000]

In [44]:
df

name  age           occupation  salary
0     mark   23    software engineer   20000
1    drake   20               tester   30000
2     mark   24              dev ops   12300
3  prakhar   23     machine learning  120000
4    henry   23  full stack engineer  100000

In [48]:
df.drop("salary",axis=1)

name  age           occupation
0     mark   23    software engineer
1    drake   20               tester
2     mark   24              dev ops
3  prakhar   23     machine learning
4    henry   23  full stack engineer

In [49]:
df.drop(["salary"],axis=1)

name  age           occupation
0     mark   23    software engineer
1    drake   20               tester
2     mark   24              dev ops
3  prakhar   23     machine learning
4    henry   23  full stack engineer

In [51]:
df.drop(["salary"],axis=1,inplace=True)

### simple modification to data frame

In [54]:
df["salary"]=[20000,30000,12300,120000,100000]

In [55]:
df

name  age           occupation  salary
0     mark   23    software engineer   20000
1    drake   20               tester   30000
2     mark   24              dev ops   12300
3  prakhar   23     machine learning  120000
4    henry   23  full stack engineer  100000

In [56]:
df["salary"]=df["salary"]+10000

In [57]:
df

name  age           occupation  salary
0     mark   23    software engineer   30000
1    drake   20               tester   40000
2     mark   24              dev ops   22300
3  prakhar   23     machine learning  130000
4    henry   23  full stack engineer  110000

In [58]:
df.describe()

age         salary
count   5.000000       5.000000
mean   22.600000   66460.000000
std     1.516575   49781.100832
min    20.000000   22300.000000
25%    23.000000   30000.000000
50%    23.000000   40000.000000
75%    23.000000  110000.000000
max    24.000000  130000.000000

In [59]:
df2=pd.read_csv("./employee_data.csv")

In [60]:
df2

EmployeeID FirstName LastName  Gender                          Email  \
0            1      Eric   Guzman    Male             qshelton@yahoo.com   
1            2   Kenneth   Graham    Male                 fwood@lutz.com   
2            3     Renee  Hendrix  Female       clinealicia@thompson.net   
3            4       Jon   Curtis    Male         cassandrawest@reed.com   
4            5  Michelle   Harris  Female      joannacarlson@hotmail.com   
..         ...       ...      ...     ...                            ...   
95          96   Anthony     Carr   Other          matthew43@hotmail.com   
96          97  Kimberly  Stevens  Female  nathangriffin@webb-david.info   
97          98       Dan     Cole    Male           evanssusan@gmail.com   
98          99   Miranda  Daniels  Female               sberry@lucas.biz   
99         100     David  Hammond   Other          daniel45@stephens.biz   

                   Phone DateOfBirth        Department     Position  \
0      602-770-5338x8453  1980-10-19  Customer Support    Developer   
1           752-724-2100  1981-08-21           Finance      Manager   
2          (332)917-4497  1969-11-29  Customer Support    Developer   
3       001-474-493-8117  1964-01-29  Customer Support     Engineer   
4             9052247567  1987-02-13                IT    Executive   
..                   ...         ...               ...          ...   
95            5334510340  2000-11-10             Sales     Engineer   
96     083-646-8989x5290  2001-05-23         Marketing  Coordinator   
97  001-434-455-0516x808  1967-07-28  Customer Support    Developer   
98     805-269-8837x5422  1968-10-21             Legal   Consultant   
99  001-827-420-0810x057  1970-12-05           Finance      Manager   

       Salary    HireDate  
0    53233.92  2019-06-07  
1    65301.83  2016-05-26  
2    61248.82  2016-12-28  
3   112405.32  2015-02-15  
4    75245.89  2015-02-13  
..        ...         ...  
95   58246.58  2015-03-11  
96   53399.28  2015-04-25  
97   46361.76  2015-12-29  
98  109108.30  2023-12-02  
99   99458.56  2023-03-16  

[100 rows x 11 columns]

In [63]:
# return first five rows by default
df2.head(4)
# return the last five rows by default
df2.tail()

EmployeeID FirstName LastName  Gender                     Email  \
0           1      Eric   Guzman    Male        qshelton@yahoo.com   
1           2   Kenneth   Graham    Male            fwood@lutz.com   
2           3     Renee  Hendrix  Female  clinealicia@thompson.net   
3           4       Jon   Curtis    Male    cassandrawest@reed.com   

               Phone DateOfBirth        Department   Position     Salary  \
0  602-770-5338x8453  1980-10-19  Customer Support  Developer   53233.92   
1       752-724-2100  1981-08-21           Finance    Manager   65301.83   
2      (332)917-4497  1969-11-29  Customer Support  Developer   61248.82   
3   001-474-493-8117  1964-01-29  Customer Support   Engineer  112405.32   

     HireDate  
0  2019-06-07  
1  2016-05-26  
2  2016-12-28  
3  2015-02-15

In [64]:
# to get the types of each element data types
df2.dtypes

EmployeeID       int64
FirstName       object
LastName        object
Gender          object
Email           object
Phone           object
DateOfBirth     object
Department      object
Position        object
Salary         float64
HireDate        object
dtype: object

In [67]:
df2.isnull().any()

EmployeeID     False
FirstName      False
LastName       False
Gender         False
Email          False
Phone          False
DateOfBirth    False
Department     False
Position       False
Salary         False
HireDate       False
dtype: bool

In [69]:
# sorting the data by column
df2.sort_values(by="Salary",ascending=True)

EmployeeID  FirstName  LastName  Gender                       Email  \
51          52     Marcus  Sullivan    Male         nthompson@gmail.com   
66          67  Christina    Hughes  Female        vangashley@gmail.com   
78          79     Rachel   Wallace   Other          jodi68@hotmail.com   
17          18     Kristy    Garcia    Male    aaronmathews@hotmail.com   
62          63     Amanda     White   Other            erin38@yahoo.com   
..         ...        ...       ...     ...                         ...   
22          23    Michael    Tanner   Other     christopher25@yahoo.com   
43          44      Chase     Smith   Other  williamskristen@knight.org   
39          40   Jennifer    Dodson  Female          dana77@hotmail.com   
14          15     Jeremy      Park  Female   kentshawn@lucas-lyons.com   
65          66   Jonathan   Sanders    Male           dawn32@torres.net   

                    Phone DateOfBirth        Department     Position  \
51       509.153.7605x659  2002-06-21             Sales   Consultant   
66   001-549-522-8099x747  1966-07-21  Customer Support      Analyst   
78           971-858-7973  1966-08-05                HR   Consultant   
17          (896)216-1584  1983-10-28        Operations   Consultant   
62        +1-216-564-7673  2002-01-03             Legal      Analyst   
..                    ...         ...               ...          ...   
22        +1-969-734-8606  1981-05-06                IT   Consultant   
43  001-645-148-3529x0962  1991-10-23           Finance      Analyst   
39     603.978.2726x26377  2002-02-04                IT     Engineer   
14     749.320.5618x21043  1973-01-05           Finance  Coordinator   
65       370-214-0089x158  1964-01-06  Customer Support  Coordinator   

       Salary    HireDate  
51   40095.79  2018-04-06  
66   41737.69  2024-03-04  
78   43197.75  2016-02-03  
17   43324.80  2018-11-05  
62   44321.74  2018-01-05  
..        ...         ...  
22  116839.71  2024-03-29  
43  118144.97  2024-06-20  
39  118349.29  2016-05-25  
14  118759.28  2017-03-08  
65  119406.27  2023-04-13  

[100 rows x 11 columns]

Patient_ID           Name  Age  Gender   Disease    Income  \
0          10001      Patient_1   46    Male       NaN   90000.0   
1          10002      Patient_2   86  Female    Asthma   90000.0   
2          10003      Patient_3   64    Male    Asthma   50000.0   
3          10004      Patient_4   79  Female  Diabetes   50000.0   
4          10005      Patient_5   86    Male  Covid-19  120000.0   
...          ...            ...  ...     ...       ...       ...   
9995       19996   Patient_9996   44  Female       NaN   90000.0   
9996       19997   Patient_9997   29    Male  Covid-19   50000.0   
9997       19998   Patient_9998   79  Female       Flu   70000.0   
9998       19999   Patient_9999   69  Female       Flu  150000.0   
9999       20000  Patient_10000   65    Male       NaN       NaN   

      Days_Admitted  Treatment_Cost  Discharged  
0              21.0            9816        True  
1              20.0            8126       False  
2               6.0            9192       False  
3               4.0            5505        True  
4              25.0            7881        True  
...             ...             ...         ...  
9995           22.0            9608       False  
9996           15.0            1316       False  
9997           28.0            3963       False  
9998           10.0            2091        True  
9999           16.0            6078        True  

[10000 rows x 9 columns]