## Assignment_1

In [1]:
import numpy as np

In [21]:
#creating a array in numpy with random integer bwtween 1 to 20
arr=np.random.randint(1,20,size=25).reshape(5,5)
# replacing the third colm with 0
arr[:,2]=1
arr
# creating an array with shape 4*4 with values ranging from 1 to 12
arr=np.array([x for x in range(1,17)]).reshape(4,4)
# now turining all the diagonal values to 0

for i in range(0,arr.shape[0]):
 arr[i,i]=1
arr
# you can also use the function called fill_diagnol to replace the arrays diagnol with the custom value
np.fill_diagonal(arr,2)
arr


array([[ 2,  2,  3,  4],
       [ 5,  2,  7,  8],
       [ 9, 10,  2, 12],
       [13, 14, 15,  2]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
#last indexing is always exclusive
arr=np.array([x for x in range(1,37)]).reshape(6,6)
print(arr)
print(arr[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [34]:
arr=np.random.randint(10000,size=12).reshape(3,4)
print(arr)
# subtraction
print("subtraction")
print(arr-10)
# addition
print("addition")
print(arr+10)
#computing the rowwise arithmetic operations
print("------------------------------------------------")
print(arr)
print("perform the arithmetic operation")
arr[1:2]=arr[1:2]+23
print(arr)

[[ 533 2200 5433 3244]
 [6122 4654 9762 9384]
 [1977  517 7417 8229]]
subtraction
[[ 523 2190 5423 3234]
 [6112 4644 9752 9374]
 [1967  507 7407 8219]]
addition
[[ 543 2210 5443 3254]
 [6132 4664 9772 9394]
 [1987  527 7427 8239]]
------------------------------------------------
[[ 533 2200 5433 3244]
 [6122 4654 9762 9384]
 [1977  517 7417 8229]]
perform the arithmetic operation
[[ 533 2200 5433 3244]
 [6145 4677 9785 9407]
 [1977  517 7417 8229]]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [52]:
arr=np.random.randint(100000,size=25).reshape(5,5)
#mean
print("mean of the dataset:",np.mean(arr))
#median 
print("median of the dataset:",np.median(arr))
# finding the mode of the daytaset
import scipy as scp
print(arr)
print("mode of the dataset:",scp.stats.mode(arr,axis=0,keepdims=True))


mean of the dataset: 38632.52
median of the dataset: 33772.0
[[70301 17057  3535 59591 39794]
 [82195 40818 15013 30825 48688]
 [ 9627  7556 11481 33772 53053]
 [58951 12076 73898 30530 73074]
 [ 4147 13906 76001 90987  8937]]
mode of the dataset: ModeResult(mode=array([[ 4147,  7556,  3535, 30530,  8937]]), count=array([[1, 1, 1, 1, 1]]))
